name: SwiftLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Cache SwiftLint
      uses: actions/cache@v4
      with:
        path: /usr/local/Cellar/swiftlint
        key: swiftlint-${{ runner.os }}-v1
        restore-keys: |
          swiftlint-${{ runner.os }}-
    - name: Install SwiftLint
      if: steps.cache.outputs.cache-hit != 'true'
      run: brew install swiftlint
    - name: Run SwiftLint
      run: swiftlint --strict
